branches:
  only:
    - master
    - /^.*travis.*$/
  except:
      - /^v\d+\.\d+\.\d+$/


dist: trusty
sudo: false
install: true
language: java

jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: "svenwesterlaken-github"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
